### ISSUE TITLE
Different output in VS Code and FemCad

### ISSUE THREAD

**Issue by jpodval** [kuboja/fcs-vscode#1]
Ahoj Honzo, narazil jsem na tento rozdíl ve výstupu a trochu mě zarazil, tak kdybys věděl, čím to je, a uměl to nějak opravit, bylo by to fajn (jinak si ten tvůj doplněk do VS Code zaslouží jen nekončící pochvaly:-))

Děje se mi to na souboru C:\GitHub\fcs-gsi\HiStruct_BuildingConfigurator\Openings\OpeningsBOM.fcs ve větvi hbc-2017-deve-JP po commitu 648d7d1dc5d5a81b5a9115c5d044cbfb412baaf7.

Když napíšu ve VS Code řádku:

print bomItemsCollectionWalls.Select(i => i.Buckets[0].Items)

a dám F5, tak se objeví výsledek

> SyntaxError 'C:\Users\jirip\AppData\Local\Temp\fcs-vscode\runner\temp_xbuhvarne.fcs':
> Expected ')' at (3,1)
![image](https://user-images.githubusercontent.com/30626579/33799324-91c13816-dd29-11e7-9828-e1d71c2cc60e.png)

Což mi přišlo divné, tak jsem to zkusil s tím samým souborem a příkazem ve FemCadu a tam už se vypíše podle mně správně:

Opening 'OpeningsBOM.fcs' ...1.376 s
 [
  [
    dParts[0].dParts[0].gbPart. = OpeningSimple(origin:{1 0 1}, axes:{{1 0 0},{0 0 1},{0 -1 0}}){},
    dParts[1].dParts[0].gbPart. = OpeningSimple(origin:{3 0 1}, axes:{{1 0 0},{0 0 1},{0 -1 0}}){},
    dParts[1].dParts[1].gbPart. = OpeningSimple(origin:{3 0 2.25}, axes:{{1 0 0},{0 0 1},{0 -1 0}}){},
    dParts[1].dParts[2].gbPart. = OpeningSimple(origin:{3 0 3.5}, axes:{{1 0 0},{0 0 1},{0 -1 0}}){},
...atd
![image](https://user-images.githubusercontent.com/30626579/33799317-799f6c6c-dd29-11e7-8c53-faec6059ae78.png)

**Comment by kuboja** [comment]
Díky.

Přímé vyhodnocování ještě plně nepodporuji... je to celkem problém... protože bys mohl chtít vypsat něco jako pole[iprvek] přičež by iprvek byl proměnná a to zatím nelze...

Abys získal výpis stačí kód upravit například tak, že si nejdříve vložíš požadovaný výstup do proměnné:
testPrint := bomItemsCollectionWalls.Select(i => i.Buckets[0].Items)
#print testPrint

![image](https://user-images.githubusercontent.com/1344559/33806614-2e9cf1c4-ddcb-11e7-94bd-8b4de3369342.png)

Spustit by měl jít jak řádek s komentářem (řádek 31), tak i řádek bez komentáře (řádek 30). Takže psát řádek 31 není třeba...

**Comment by kuboja** [comment]
Pro správné fungování výpisu musíš použít novou verzi doplňku, protože pokud výpis obsahoval text "Openings", tak se celý řádek nevypsal :) ale už to funguje...

![image](https://user-images.githubusercontent.com/1344559/33806665-e313e89c-ddcb-11e7-9e31-a19ffc1d2b8d.png)

Za další připomínky budu rád :)

**Comment by jpodval** [comment]
Díky za vysvětlení. Dalo se čekat, že problém bude spíš na straně uživatele:-)
Je fakt výborná věc. Tak si s ní jdu hrát dál:-)
